# Generated by Django 3.2.16 on 2023-02-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test', models.CharField(max_length=500)),
            ],
        ),
    ]
