# Generated by Django 3.2.16 on 2023-02-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='box_info',
            fields=[
                ('box_id', models.IntegerField(primary_key=True, serialize=False)),
                ('box_name', models.CharField(max_length=500)),
                ('day_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='card_info',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=500)),
                ('eff_card', models.CharField(max_length=500)),
                ('rarity_card', models.CharField(max_length=3)),
                ('photo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='card_sale',
            fields=[
                ('sale_id', models.IntegerField(primary_key=True, serialize=False)),
                ('photo_upload', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=500)),
                ('sale_day', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
