# Generated by Django 3.2.16 on 2023-02-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_info',
            name='box_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card_info',
            name='price_adv',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
