# Generated by Django 3.2.16 on 2023-02-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230216_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='box_info',
            name='num_rarity_c',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box_info',
            name='num_rarity_r',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box_info',
            name='num_rarity_rr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box_info',
            name='num_rarity_rrr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box_info',
            name='number_of_card',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
