# Generated by Django 4.1.4 on 2023-02-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0002_delete_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="nation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nation", models.CharField(max_length=500)),
            ],
        ),
    ]
