# Generated by Django 3.2.16 on 2023-02-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230216_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_sale',
            name='card_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card_sale',
            name='sale_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card_sale',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='saler_id',
            field=models.IntegerField(default=0),
        ),
    ]
