# Generated by Django 4.1.4 on 2023-02-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="card_info",
            fields=[
                ("card_id", models.AutoField(primary_key=True, serialize=False)),
                ("box_id", models.IntegerField()),
                ("card_name", models.CharField(max_length=500)),
                ("rarity_card", models.CharField(max_length=3)),
                ("nation", models.CharField(max_length=500)),
                ("eff_card", models.CharField(max_length=500)),
                ("price_adv", models.IntegerField()),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="ricado_mk2.jpg",
                        null=True,
                        upload_to="card_img",
                    ),
                ),
            ],
        ),
    ]
