# Generated by Django 3.2.16 on 2023-02-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230216_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_info',
            name='photo_test',
            field=models.ImageField(null=True, upload_to='home/upload_img'),
        ),
    ]
