# Generated by Django 4.1.4 on 2023-02-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_box_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="card_sale",
            fields=[
                ("sale_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField(default=0)),
                ("card_id", models.IntegerField(default=0)),
                ("sale_price", models.IntegerField(default=0)),
                ("photo_upload", models.CharField(max_length=500)),
            ],
        ),
    ]
