# Generated by Django 4.1.4 on 2023-02-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_card_sale"),
    ]

    operations = [
        migrations.CreateModel(
            name="transaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("card_id", models.IntegerField(default=0)),
                ("saler_id", models.IntegerField(default=0)),
                ("buyer_id", models.IntegerField(default=0)),
                ("card_name", models.CharField(max_length=500)),
                ("sale_day", models.DateTimeField(auto_now_add=True)),
                ("price", models.IntegerField(default=0)),
            ],
        ),
    ]
