# Generated by Django 4.1.4 on 2023-02-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_card_info_from_box"),
    ]

    operations = [
        migrations.AddField(
            model_name="box_info",
            name="bt_num",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
