# Generated by Django 4.1.4 on 2023-02-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_card_info_from_nation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card_info",
            name="box_id",
        ),
    ]
