# Generated by Django 4.1.4 on 2023-02-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_remove_card_info_box_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="box_infromation",
            fields=[
                (
                    "box_code",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                ("box_name_test", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="card_infromation",
            fields=[
                (
                    "card_id_key",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                (
                    "card_photo",
                    models.ImageField(
                        blank=True,
                        default="ricado_mk2.jpg",
                        null=True,
                        upload_to="card_img",
                    ),
                ),
                (
                    "from_box",
                    models.ForeignKey(
                        on_delete=models.SET("promo"), to="home.box_infromation"
                    ),
                ),
            ],
        ),
    ]
