# Generated by Django 4.1.4 on 2023-02-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_box_has_nation_delete_card_infromation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="box_infromation",
            old_name="box_name_test",
            new_name="box_name_n",
        ),
    ]
