# Generated by Django 4.1.4 on 2023-02-24 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_nation_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box_has_nation",
            name="has_nation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.nation_name",
            ),
        ),
    ]
