# Generated by Django 4.1.4 on 2023-02-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_alter_box_has_nation_has_nation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nation_name",
            name="nation_nam",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
