# Generated by Django 4.1.4 on 2023-02-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_alter_nation_name_nation_nam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box_infromation",
            name="box_code",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
