# Generated by Django 3.2.16 on 2023-02-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_card_infomation'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_infomation',
            name='grade',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
