# Generated by Django 3.2.16 on 2023-02-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_card_infomation_from_nation'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_infomation',
            name='fourth_effect_card',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='card_infomation',
            name='second_effect_card',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='card_infomation',
            name='third_effect_card',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
