# Generated by Django 3.2.16 on 2023-02-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20230228_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_infomation',
            name='effect_card',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
