# Generated by Django 3.2.16 on 2023-02-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_card_info_photo_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_info',
            name='photo_test',
        ),
        migrations.AddField(
            model_name='card_info',
            name='photo',
            field=models.ImageField(blank=True, default='ricado_mk2.jpg', null=True, upload_to='card_img'),
        ),
    ]
