# Generated by Django 3.2.16 on 2023-02-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_card_infomation_fifth_effect_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_infomation',
            name='effect_card',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='card_infomation',
            name='fifth_effect_card',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='card_infomation',
            name='fourth_effect_card',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='card_infomation',
            name='second_effect_card',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='card_infomation',
            name='third_effect_card',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
