# Generated by Django 3.2.16 on 2023-02-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20230228_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card_infomation',
            old_name='from_nation',
            new_name='card_from_nation',
        ),
    ]
