# Generated by Django 4.1.4 on 2023-03-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0030_nation_name_nation_favicon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card_infomation",
            name="grade",
            field=models.IntegerField(default=0),
        ),
    ]
