# Generated by Django 4.1.4 on 2023-03-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0032_alter_nation_name_nation_favicon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card_infomation",
            name="effect_card",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
