# Generated by Django 4.1.4 on 2023-03-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0033_alter_card_infomation_effect_card"),
    ]

    operations = [
        migrations.DeleteModel(
            name="transaction",
        ),
    ]
