# Generated by Django 4.1.4 on 2023-03-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0034_delete_transaction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="card_sale",
        ),
    ]
