# Generated by Django 4.1.4 on 2023-03-02 10:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_auto_20230302_0030"),
        ("home", "0035_delete_card_sale"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardWhoWantToSale",
            fields=[
                (
                    "saleId",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("day_created", models.DateTimeField(auto_now_add=True)),
                (
                    "card_photo",
                    models.ImageField(
                        blank=True,
                        default="no_infomation.png",
                        null=True,
                        upload_to="card_img",
                    ),
                ),
                ("sale_price", models.IntegerField(default=0, null=True)),
                (
                    "userWhoWantSale",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.profile",
                    ),
                ),
            ],
        ),
    ]
