# Generated by Django 4.1.4 on 2023-03-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0036_cardwhowanttosale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardwhowanttosale",
            name="card_photo",
        ),
        migrations.AddField(
            model_name="cardwhowanttosale",
            name="cardPhotoWhoWantSale",
            field=models.ImageField(
                blank=True,
                default="no_infomation.png",
                null=True,
                upload_to="sale_photo",
            ),
        ),
    ]
