# Generated by Django 4.1.4 on 2023-03-02 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0037_remove_cardwhowanttosale_card_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardwhowanttosale",
            name="cardFromNation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.nation_name",
            ),
        ),
        migrations.AddField(
            model_name="cardwhowanttosale",
            name="cardSaleCode",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.card_infomation",
            ),
        ),
    ]
