# Generated by Django 4.1.4 on 2023-03-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0038_cardwhowanttosale_cardfromnation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardwhowanttosale",
            name="userWhoWantSale",
        ),
    ]
