# Generated by Django 4.1.4 on 2023-03-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0039_remove_cardwhowanttosale_userwhowantsale"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardwhowanttosale",
            name="test",
            field=models.IntegerField(default=0),
        ),
    ]
