# Generated by Django 4.1.4 on 2023-03-02 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_auto_20230302_0030"),
        ("home", "0041_remove_cardwhowanttosale_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardwhowanttosale",
            name="userWhoWantSale",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.profile",
            ),
        ),
    ]
