# Generated by Django 4.1.4 on 2023-03-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0042_cardwhowanttosale_userwhowantsale"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cardwhowanttosale",
            old_name="cardSaleCode",
            new_name="card_code",
        ),
    ]
