# Generated by Django 4.1.4 on 2023-03-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0045_alter_cardwhowanttosale_userwhowantsale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardwhowanttosale",
            name="cardPhotoWhoWantSale",
            field=models.ImageField(
                default="no_infomation.png", null=True, upload_to="sale_photo"
            ),
        ),
        migrations.AlterField(
            model_name="cardwhowanttosale",
            name="userWhoWantSale",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
