# Generated by Django 4.1.4 on 2023-03-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0048_alter_cardwhowanttosale_userwhowantsale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardwhowanttosale",
            name="cardPhotoWhoWantSale",
        ),
        migrations.RemoveField(
            model_name="cardwhowanttosale",
            name="userWhoWantSale",
        ),
    ]
