# Generated by Django 4.1.4 on 2023-03-03 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0052_alter_cardwhowanttosale_userwhowantsale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardwhowanttosale",
            name="userWhoWantSale",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
