# Generated by Django 4.1.4 on 2023-03-03 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_auto_20230302_0030"),
        ("home", "0056_alter_cardwhowanttosale_userwhowantsale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardwhowanttosale",
            name="userWhoWantSale",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.profile",
            ),
        ),
    ]
