# Generated by Django 4.1.4 on 2023-03-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0058_cardwhowanttosale_cardphotowhowantsale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardwhowanttosale",
            name="userWhoWantSale",
        ),
        migrations.AlterField(
            model_name="cardwhowanttosale",
            name="userNameWhoWantSale",
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
