# Generated by Django 4.1.4 on 2023-03-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0067_transaction_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction_table",
            name="buyerPhone",
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
    ]
