# Generated by Django 4.1.4 on 2023-03-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0073_alter_transaction_table_buyeraddr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction_table",
            name="price_detal",
            field=models.IntegerField(default=0),
        ),
    ]
