# Generated by Django 4.1.4 on 2023-03-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0075_alter_card_infomation_price_average"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card_infomation",
            name="price_average",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
