# Generated by Django 4.1.4 on 2023-03-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0076_alter_card_infomation_price_average"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction_table",
            name="price_detal",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
