# Generated by Django 4.1.4 on 2023-03-08 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0077_alter_transaction_table_price_detal"),
    ]

    operations = [
        migrations.CreateModel(
            name="auction",
            fields=[
                (
                    "auction_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("card", models.CharField(max_length=100)),
                ("timer", models.DateTimeField()),
            ],
        ),
    ]
