# Generated by Django 4.1.4 on 2023-03-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0078_auction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="auction",
        ),
    ]
