# Generated by Django 3.2.16 on 2023-03-12 09:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_delete_auction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('userWhoRateThis', models.CharField(max_length=100, null=True)),
                ('rateUser', models.CharField(max_length=100, null=True)),
                ('rate', models.FloatField()),
                ('rating_day', models.DateTimeField(auto_now_add=True)),
                ('rate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rating_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cardwhowanttosale')),
            ],
        ),
    ]
