# Generated by Django 3.2.16 on 2023-03-12 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.transaction_table'),
        ),
    ]
