# Generated by Django 3.2.16 on 2023-03-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_auto_20230312_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rateTxt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
