# Generated by Django 3.2.16 on 2023-03-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_alter_rating_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_table',
            name='is_rate',
            field=models.BooleanField(default=False),
        ),
    ]
