# Generated by Django 4.1.4 on 2023-03-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0089_alter_cardwhowanttosale_cardphotowhowantsale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="box_has_nation",
            name="has_nation",
        ),
        migrations.RemoveField(
            model_name="box_has_nation",
            name="id_box",
        ),
        migrations.DeleteModel(
            name="box_info",
        ),
        migrations.DeleteModel(
            name="box_has_nation",
        ),
        migrations.DeleteModel(
            name="box_infromation",
        ),
    ]
