# Generated by Django 3.2.16 on 2023-02-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=500)),
                ('sale', models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller')], default='customer', max_length=50)),
            ],
        ),
    ]
