# Generated by Django 4.1.4 on 2023-03-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_user_user_photo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="user",
        ),
    ]
