# Generated by Django 4.1.4 on 2023-03-01 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0005_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="user",
            fields=[
                ("username", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=60, unique=True)),
                ("password", models.CharField(max_length=100, unique=True)),
                ("address", models.CharField(max_length=500)),
                (
                    "sale",
                    models.CharField(
                        choices=[("customer", "Customer"), ("seller", "Seller")],
                        default="customer",
                        max_length=50,
                    ),
                ),
                (
                    "user_photo",
                    models.ImageField(
                        blank=True,
                        default="icon-van.jpg",
                        null=True,
                        upload_to="user_icon",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
