# Generated by Django 4.1.4 on 2023-03-01 08:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0006_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="user",
            new_name="profile",
        ),
    ]
