# Generated by Django 4.1.4 on 2023-03-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_alter_profile_name_alter_profile_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="username",
        ),
    ]
